---

- name: "Install: Setup PGSQL"
  remote_user: root
  hosts: pgsql
  gather_facts: yes
  pre_tasks:
  - name: apt-get update
    apt: update_cache=yes cache_valid_time=86400

  tasks:

  - name: "Install: Build hosts file"
    lineinfile: dest=/etc/hosts regexp='{{ ansible_default_ipv4.address }}' line="{{ ansible_default_ipv4.address }} {{ ansible_hostname }}" state=present

  - name: "Install: install packages"
    apt: pkg={{ item }}
    with_items:
    - postgresql
    - postgresql-contrib
    - postgresql-client
    - git
    - libpq-dev
    - python-psycopg2
    - python-pip
    - python-dev
    - daemontools
    - libffi-dev
    - lzop

  - name: "Install: Upgrade pip"
    pip: name={{item}} extra_args=--upgrade
    with_items:
      - pip
